export const Country = [
  {"code":"AD","label":"Andorra","phone":"376","zh":"安道尔"},
  {"code":"AE","label":"United Arab Emirates","phone":"971","zh":"阿拉伯联合酋长国"},
  {"code":"AF","label":"Afghanistan","phone":"93","zh":"阿富汗"},
  {"code":"AG","label":"Antigua and Barbuda","phone":"1-268","zh":"安提瓜和巴布达"},
  {"code":"AI","label":"Anguilla","phone":"1-264","zh":"安圭拉"},
  {"code":"AL","label":"Albania","phone":"355","zh":"阿尔巴尼亚"},
  {"code":"AM","label":"Armenia","phone":"374","zh":"亚美尼亚"},
  {"code":"AO","label":"Angola","phone":"244","zh":"安哥拉"},
  {"code":"AQ","label":"Antarctica","phone":"672","zh":"南极"},
  {"code":"AR","label":"Argentina","phone":"54","zh":"阿根廷"},
  {"code":"AS","label":"American Samoa","phone":"1-684","zh":"美属萨摩亚"},
  {"code":"AT","label":"Austria","phone":"43","zh":"奥地利"},
  {"code":"AU","label":"Australia","phone":"61","zh":"澳大利亚"},
  {"code":"AW","label":"Aruba","phone":"297","zh":"阿鲁巴"},
  {"code":"AX","label":"Alland Islands","phone":"358","zh":"奥兰群岛"},
  {"code":"AZ","label":"Azerbaijan","phone":"994","zh":"阿塞拜疆"},
  {"code":"BA","label":"Bosnia and Herzegovina","phone":"387","zh":"波斯尼亚和黑塞哥维那"},
  {"code":"BB","label":"Barbados","phone":"1-246","zh":"巴巴多斯"},
  {"code":"BD","label":"Bangladesh","phone":"880","zh":"孟加拉"},
  {"code":"BE","label":"Belgium","phone":"32","zh":"比利时"},
  {"code":"BF","label":"Burkina Faso","phone":"226","zh":"布基纳法索"},
  {"code":"BG","label":"Bulgaria","phone":"359","zh":"保加利亚"},
  {"code":"BH","label":"Bahrain","phone":"973","zh":"巴林"},
  {"code":"BI","label":"Burundi","phone":"257","zh":"布隆迪"},
  {"code":"BJ","label":"Benin","phone":"229","zh":"贝宁"},
  {"code":"BL","label":"Saint Barthelemy","phone":"590","zh":"圣巴托洛缪"},
  {"code":"BM","label":"Bermuda","phone":"1-441","zh":"百慕大"},
  {"code":"BN","label":"Brunei Darussalam","phone":"673","zh":"文莱达鲁萨兰国"},
  {"code":"BO","label":"Bolivia","phone":"591","zh":"玻利维亚"},
  {"code":"BR","label":"Brazil","phone":"55","zh":"巴西"},
  {"code":"BS","label":"Bahamas","phone":"1-242","zh":"巴哈马"},
  {"code":"BT","label":"Bhutan","phone":"975","zh":"不丹"},
  {"code":"BV","label":"Bouvet Island","phone":"47","zh":"布维岛"},
  {"code":"BW","label":"Botswana","phone":"267","zh":"博茨瓦纳"},
  {"code":"BY","label":"Belarus","phone":"375","zh":"白俄罗斯"},
  {"code":"BZ","label":"Belize","phone":"501","zh":"伯利兹"},
  {"code":"CA","label":"Canada","phone":"1","zh":"加拿大"},
  {"code":"CC","label":"Cocos (Keeling) Islands","phone":"61","zh":"可可斯群岛"},
  {"code":"CD","label":"Congo, Republic of the","phone":"242","zh":"刚果民主共和国"},
  {"code":"CF","label":"Central African Republic","phone":"236","zh":"中非"},
  {"code":"CG","label":"Congo, Democratic Republic of the","phone":"243","zh":"刚果"},
  {"code":"CH","label":"Switzerland","phone":"41","zh":"瑞士"},
  {"code":"CI","label":"Cote d'Ivoire","phone":"225","zh":"科特迪瓦"},
  {"code":"CK","label":"Cook Islands","phone":"682","zh":"库克群岛"},
  {"code":"CL","label":"Chile","phone":"56","zh":"智利"},
  {"code":"CM","label":"Cameroon","phone":"237","zh":"喀麦隆"},
  {"code":"CN","label":"China","phone":"86","zh":"中国"},
  {"code":"CO","label":"Colombia","phone":"57","zh":"哥伦比亚"},
  {"code":"CR","label":"Costa Rica","phone":"506","zh":"哥斯达黎加"},
  {"code":"CU","label":"Cuba","phone":"53","zh":"古巴"},
  {"code":"CV","label":"Cape Verde","phone":"238","zh":"佛得角"},
  {"code":"CW","label":"Curacao","phone":"599","zh":"库拉索岛"},
  {"code":"CX","label":"Christmas Island","phone":"61","zh":"圣诞岛"},
  {"code":"CY","label":"Cyprus","phone":"357","zh":"塞浦路斯"},
  {"code":"CZ","label":"Czech Republic","phone":"420","zh":"捷克斯洛伐克共和国"},
  {"code":"DE","label":"Germany","phone":"49","zh":"德国"},
  {"code":"DJ","label":"Djibouti","phone":"253","zh":"吉布提"},
  {"code":"DK","label":"Denmark","phone":"45","zh":"丹麦"},
  {"code":"DM","label":"Dominica","phone":"1-767","zh":"多米尼加"},
  {"code":"DO","label":"Dominican Republic","phone":"1-809","zh":"多米尼加共和国"},
  {"code":"DZ","label":"Algeria","phone":"213","zh":"阿尔及利亚"},
  {"code":"EC","label":"Ecuador","phone":"593","zh":"厄瓜多尔"},
  {"code":"EE","label":"Estonia","phone":"372","zh":"爱沙尼亚"},
  {"code":"EG","label":"Egypt","phone":"20","zh":"埃及"},
  {"code":"EH","label":"Western Sahara","phone":"212","zh":"西撒哈拉"},
  {"code":"ER","label":"Eritrea","phone":"291","zh":"厄立特里亚"},
  {"code":"ES","label":"Spain","phone":"34","zh":"西班牙"},
  {"code":"ET","label":"Ethiopia","phone":"251","zh":"埃塞俄比亚"},
  {"code":"FI","label":"Finland","phone":"358","zh":"芬兰"},
  {"code":"FJ","label":"Fiji","phone":"679","zh":"斐济"},
  {"code":"FK","label":"Falkland Islands (Malvinas)","phone":"500","zh":"福克兰群岛"},
  {"code":"FM","label":"Micronesia, Federated States of","phone":"691","zh":"密克罗尼西亚"},
  {"code":"FO","label":"Faroe Islands","phone":"298","zh":"法罗群岛"},
  {"code":"FR","label":"France","phone":"33","zh":"法国"},
  {"code":"GA","label":"Gabon","phone":"241","zh":"加蓬"},
  {"code":"GB","label":"United Kingdom","phone":"44","zh":"英国"},
  {"code":"GD","label":"Grenada","phone":"1-473","zh":"格林纳达"},
  {"code":"GE","label":"Georgia","phone":"995","zh":"格鲁吉亚"},
  {"code":"GF","label":"French Guiana","phone":"594","zh":"法属圭亚那"},
  {"code":"GG","label":"Guernsey","phone":"44","zh":"根西岛"},
  {"code":"GH","label":"Ghana","phone":"233","zh":"加纳"},
  {"code":"GI","label":"Gibraltar","phone":"350","zh":"直布罗陀"},
  {"code":"GL","label":"Greenland","phone":"299","zh":"格陵兰"},
  {"code":"GM","label":"Gambia","phone":"220","zh":"冈比亚"},
  {"code":"GN","label":"Guinea","phone":"224","zh":"几内亚"},
  {"code":"GP","label":"Guadeloupe","phone":"590","zh":"瓜德罗普岛"},
  {"code":"GQ","label":"Equatorial Guinea","phone":"240","zh":"赤道几内亚"},
  {"code":"GR","label":"Greece","phone":"30","zh":"希腊"},
  {"code":"GS","label":"South Georgia and the South Sandwich Islands","phone":"500","zh":"南乔治亚和南"},
  {"code":"GT","label":"Guatemala","phone":"502","zh":"危地马拉"},
  {"code":"GU","label":"Guam","phone":"1-671","zh":"关岛"},
  {"code":"GW","label":"Guinea-Bissau","phone":"245","zh":"几内亚比绍"},
  {"code":"GY","label":"Guyana","phone":"592","zh":"圭亚那"},
  {"code":"HK","label":"Hong Kong","phone":"852","zh":"香港（中国）"},
  {"code":"HM","label":"Heard Island and McDonald Islands","phone":"672","zh":"贺得及麦唐纳群岛"},
  {"code":"HN","label":"Honduras","phone":"504","zh":"洪都拉斯"},
  {"code":"HR","label":"Croatia","phone":"385","zh":"克罗地亚"},
  {"code":"HT","label":"Haiti","phone":"509","zh":"海地"},
  {"code":"HU","label":"Hungary","phone":"36","zh":"匈牙利"},
  {"code":"ID","label":"Indonesia","phone":"62","zh":"印度尼西亚"},
  {"code":"IE","label":"Ireland","phone":"353","zh":"爱尔兰"},
  {"code":"IL","label":"Israel","phone":"972","zh":"以色列"},
  {"code":"IM","label":"Isle of Man","phone":"44","zh":"马恩岛"},
  {"code":"IN","label":"India","phone":"91","zh":"印度"},
  {"code":"IO","label":"British Indian Ocean Territory","phone":"246","zh":"英属印度洋领土"},
  {"code":"IQ","label":"Iraq","phone":"964","zh":"伊拉克"},
  {"code":"IR","label":"Iran, Islamic Republic of","phone":"98","zh":"伊朗"},
  {"code":"IS","label":"Iceland","phone":"354","zh":"冰岛"},
  {"code":"IT","label":"Italy","phone":"39","zh":"意大利"},
  {"code":"JE","label":"Jersey","phone":"44","zh":"泽西岛"},
  {"code":"JM","label":"Jamaica","phone":"1-876","zh":"牙买加"},
  {"code":"JO","label":"Jordan","phone":"962","zh":"约旦"},
  {"code":"JP","label":"Japan","phone":"81","zh":"日本"},
  {"code":"KE","label":"Kenya","phone":"254","zh":"肯尼亚"},
  {"code":"KG","label":"Kyrgyzstan","phone":"996","zh":"吉尔吉斯斯坦"},
  {"code":"KH","label":"Cambodia","phone":"855","zh":"柬埔寨"},
  {"code":"KI","label":"Kiribati","phone":"686","zh":"基里巴斯"},
  {"code":"KM","label":"Comoros","phone":"269","zh":"科摩罗"},
  {"code":"KN","label":"Saint Kitts and Nevis","phone":"1-869","zh":"圣基茨和尼维斯岛"},
  {"code":"KP","label":"Korea, Democratic People's Republic of","phone":"850","zh":"朝鲜"},
  {"code":"KR","label":"Korea, Republic of","phone":"82","zh":"韩国"},
  {"code":"KW","label":"Kuwait","phone":"965","zh":"科威特"},
  {"code":"KY","label":"Cayman Islands","phone":"1-345","zh":"开曼群岛"},
  {"code":"KZ","label":"Kazakhstan","phone":"7","zh":"哈萨克斯坦"},
  {"code":"LA","label":"Lao People's Democratic Republic","phone":"856","zh":"老挝"},
  {"code":"LB","label":"Lebanon","phone":"961","zh":"黎巴嫩"},
  {"code":"LC","label":"Saint Lucia","phone":"1-758","zh":"圣卢西亚"},
  {"code":"LI","label":"Liechtenstein","phone":"423","zh":"列支敦士登"},
  {"code":"LK","label":"Sri Lanka","phone":"94","zh":"斯里兰卡"},
  {"code":"LR","label":"Liberia","phone":"231","zh":"利比里亚"},
  {"code":"LS","label":"Lesotho","phone":"266","zh":"莱索托"},
  {"code":"LT","label":"Lithuania","phone":"370","zh":"立陶宛"},
  {"code":"LU","label":"Luxembourg","phone":"352","zh":"卢森堡"},
  {"code":"LV","label":"Latvia","phone":"371","zh":"拉脱维亚"},
  {"code":"LY","label":"Libya","phone":"218","zh":"利比亚"},
  {"code":"MA","label":"Morocco","phone":"212","zh":"摩洛哥"},
  {"code":"MC","label":"Monaco","phone":"377","zh":"摩纳哥"},
  {"code":"MD","label":"Moldova, Republic of","phone":"373","zh":"摩尔多瓦"},
  {"code":"ME","label":"Montenegro","phone":"382","zh":"黑山"},
  {"code":"MF","label":"Saint Martin (French part)","phone":"590","zh":"圣马丁(法属部分)"},
  {"code":"MG","label":"Madagascar","phone":"261","zh":"马达加斯加"},
  {"code":"MH","label":"Marshall Islands","phone":"692","zh":"马绍尔群岛"},
  {"code":"MK","label":"Macedonia, the Former Yugoslav Republic of","phone":"389","zh":"马其顿"},
  {"code":"ML","label":"Mali","phone":"223","zh":"马里"},
  {"code":"MM","label":"Myanmar","phone":"95","zh":"缅甸"},
  {"code":"MN","label":"Mongolia","phone":"976","zh":"蒙古"},
  {"code":"MO","label":"Macao","phone":"853","zh":"澳门 (中国)"},
  {"code":"MP","label":"Northern Mariana Islands","phone":"1-670","zh":"北马利亚纳群岛"},
  {"code":"MQ","label":"Martinique","phone":"596","zh":"马提尼克岛"},
  {"code":"MR","label":"Mauritania","phone":"222","zh":"毛里塔尼亚"},
  {"code":"MS","label":"Montserrat","phone":"1-664","zh":"蒙特塞拉特"},
  {"code":"MT","label":"Malta","phone":"356","zh":"马耳他"},
  {"code":"MU","label":"Mauritius","phone":"230","zh":"毛里求斯"},
  {"code":"MV","label":"Maldives","phone":"960","zh":"马尔代夫"},
  {"code":"MW","label":"Malawi","phone":"265","zh":"马拉维"},
  {"code":"MX","label":"Mexico","phone":"52","zh":"墨西哥"},
  {"code":"MY","label":"Malaysia","phone":"60","zh":"马来西亚"},
  {"code":"MZ","label":"Mozambique","phone":"258","zh":"莫桑比克"},
  {"code":"NA","label":"Namibia","phone":"264","zh":"纳米比亚"},
  {"code":"NC","label":"New Caledonia","phone":"687","zh":"新喀里多尼亚"},
  {"code":"NE","label":"Niger","phone":"227","zh":"尼日尔"},
  {"code":"NF","label":"Norfolk Island","phone":"672","zh":"诺福克岛"},
  {"code":"NG","label":"Nigeria","phone":"234","zh":"尼日利亚"},
  {"code":"NI","label":"Nicaragua","phone":"505","zh":"尼加拉瓜"},
  {"code":"NL","label":"Netherlands","phone":"31","zh":"荷兰"},
  {"code":"NO","label":"Norway","phone":"47","zh":"挪威"},
  {"code":"NP","label":"Nepal","phone":"977","zh":"尼泊尔"},
  {"code":"NR","label":"Nauru","phone":"674","zh":"瑙鲁"},
  {"code":"NU","label":"Niue","phone":"683","zh":"纽埃"},
  {"code":"NZ","label":"New Zealand","phone":"64","zh":"新西兰"},
  {"code":"OM","label":"Oman","phone":"968","zh":"阿曼"},
  {"code":"PA","label":"Panama","phone":"507","zh":"巴拿马"},
  {"code":"PE","label":"Peru","phone":"51","zh":"秘鲁"},
  {"code":"PF","label":"French Polynesia","phone":"689","zh":"法属波利尼西亚"},
  {"code":"PG","label":"Papua New Guinea","phone":"675","zh":"巴布亚新几内亚"},
  {"code":"PH","label":"Philippines","phone":"63","zh":"菲律宾"},
  {"code":"PK","label":"Pakistan","phone":"92","zh":"巴基斯坦"},
  {"code":"PL","label":"Poland","phone":"48","zh":"波兰"},
  {"code":"PM","label":"Saint Pierre and Miquelon","phone":"508","zh":"圣皮埃尔和密克隆岛"},
  {"code":"PN","label":"Pitcairn","phone":"870","zh":"皮特凯恩群岛"},
  {"code":"PR","label":"Puerto Rico","phone":"1","zh":"波多黎各"},
  {"code":"PS","label":"Palestine, State of","phone":"970","zh":"巴勒斯坦地区"},
  {"code":"PT","label":"Portugal","phone":"351","zh":"葡萄牙"},
  {"code":"PW","label":"Palau","phone":"680","zh":"帕劳"},
  {"code":"PY","label":"Paraguay","phone":"595","zh":"巴拉圭"},
  {"code":"QA","label":"Qatar","phone":"974","zh":"卡塔尔"},
  {"code":"RE","label":"Reunion","phone":"262","zh":"留尼汪岛"},
  {"code":"RO","label":"Romania","phone":"40","zh":"罗马尼亚"},
  {"code":"RS","label":"Serbia","phone":"381","zh":"塞尔维亚"},
  {"code":"RU","label":"Russian Federation","phone":"7","zh":"俄罗斯联邦"},
  {"code":"RW","label":"Rwanda","phone":"250","zh":"卢旺达"},
  {"code":"SA","label":"Saudi Arabia","phone":"966","zh":"沙特阿拉伯"},
  {"code":"SB","label":"Solomon Islands","phone":"677","zh":"所罗门群岛"},
  {"code":"SC","label":"Seychelles","phone":"248","zh":"塞舌尔"},
  {"code":"SD","label":"Sudan","phone":"249","zh":"苏丹"},
  {"code":"SE","label":"Sweden","phone":"46","zh":"瑞典"},
  {"code":"SG","label":"Singapore","phone":"65","zh":"新加坡"},
  {"code":"SH","label":"Saint Helena","phone":"290","zh":"圣赫勒拿"},
  {"code":"SI","label":"Slovenia","phone":"386","zh":"斯洛文尼亚"},
  {"code":"SJ","label":"Svalbard and Jan Mayen","phone":"47","zh":"斯瓦尔巴特群岛和扬马延岛"},
  {"code":"SK","label":"Slovakia","phone":"421","zh":"斯洛伐克"},
  {"code":"SL","label":"Sierra Leone","phone":"232","zh":"塞拉利昂"},
  {"code":"SM","label":"San Marino","phone":"378","zh":"圣马力诺"},
  {"code":"SN","label":"Senegal","phone":"221","zh":"塞内加尔"},
  {"code":"SO","label":"Somalia","phone":"252","zh":"索马里"},
  {"code":"SR","label":"Suriname","phone":"597","zh":"苏里南"},
  {"code":"SS","label":"South Sudan","phone":"211","zh":"南苏丹"},
  {"code":"ST","label":"Sao Tome and Principe","phone":"239","zh":"圣多美和普林西比"},
  {"code":"SV","label":"El Salvador","phone":"503","zh":"萨尔瓦多"},
  {"code":"SX","label":"Sint Maarten (Dutch part)","phone":"1-721","zh":"圣马丁岛（荷兰部分）"},
  {"code":"SY","label":"Syrian Arab Republic","phone":"963","zh":"叙利亚"},
  {"code":"SZ","label":"Swaziland","phone":"268","zh":"斯威士兰"},
  {"code":"TC","label":"Turks and Caicos Islands","phone":"1-649","zh":"特克斯和凯科斯群岛"},
  {"code":"TD","label":"Chad","phone":"235","zh":"乍得"},
  {"code":"TF","label":"French Southern Territories","phone":"262","zh":"法属南部领土"},
  {"code":"TG","label":"Togo","phone":"228","zh":"多哥"},
  {"code":"TH","label":"Thailand","phone":"66","zh":"泰国"},
  {"code":"TJ","label":"Tajikistan","phone":"992","zh":"塔吉克斯坦"},
  {"code":"TK","label":"Tokelau","phone":"690","zh":"托克劳"},
  {"code":"TL","label":"Timor-Leste","phone":"670","zh":"东帝汶"},
  {"code":"TM","label":"Turkmenistan","phone":"993","zh":"土库曼斯坦"},
  {"code":"TN","label":"Tunisia","phone":"216","zh":"突尼斯"},
  {"code":"TO","label":"Tonga","phone":"676","zh":"汤加"},
  {"code":"TR","label":"Turkey","phone":"90","zh":"土耳其"},
  {"code":"TT","label":"Trinidad and Tobago","phone":"1-868","zh":"特立尼达和多巴哥"},
  {"code":"TV","label":"Tuvalu","phone":"688","zh":"图瓦卢"},
  {"code":"TW","label":"Taiwan, Province of China","phone":"886","zh":"台湾 (中国)"},
  {"code":"TZ","label":"United Republic of Tanzania","phone":"255","zh":"坦桑尼亚"},
  {"code":"UA","label":"Ukraine","phone":"380","zh":"乌克兰"},
  {"code":"UG","label":"Uganda","phone":"256","zh":"乌干达"},
  {"code":"US","label":"United States","phone":"1","zh":"美国"},
  {"code":"UY","label":"Uruguay","phone":"598","zh":"乌拉圭"},
  {"code":"UZ","label":"Uzbekistan","phone":"998","zh":"乌兹别克斯坦"},
  {"code":"VA","label":"Holy See (Vatican City State)","phone":"379","zh":"梵蒂冈"},
  {"code":"VC","label":"Saint Vincent and the Grenadines","phone":"1-784","zh":"圣文森特和格林纳丁斯"},
  {"code":"VE","label":"Venezuela","phone":"58","zh":"委内瑞拉"},
  {"code":"VG","label":"British Virgin Islands","phone":"1-284","zh":"英属维尔京群岛"},
  {"code":"VI","label":"US Virgin Islands","phone":"1-340","zh":"英属维尔京群岛, 美国"},
  {"code":"VN","label":"Vietnam","phone":"84","zh":"越南"},
  {"code":"VU","label":"Vanuatu","phone":"678","zh":"瓦努阿图"},
  {"code":"WF","label":"Wallis and Futuna","phone":"681","zh":"瓦利斯群岛和富图纳群岛"},
  {"code":"WS","label":"Samoa","phone":"685","zh":"萨摩亚"},
  {"code":"XK","label":"Kosovo","phone":"383","zh":"科索沃"},
  {"code":"YE","label":"Yemen","phone":"967","zh":"也门"},
  {"code":"YT","label":"Mayotte","phone":"262","zh":"马约特"},
  {"code":"ZA","label":"South Africa","phone":"27","zh":"南非"},
  {"code":"ZM","label":"Zambia","phone":"260","zh":"赞比亚"},
  {"code":"ZW","label":"Zimbabwe","phone":"263","zh":"津巴布韦"}
]
export const countryToFlag = (isoCode: string) => {
  return typeof String.fromCodePoint !== 'undefined'
    ? isoCode.toUpperCase().replace(/./g, char => String.fromCodePoint(char.charCodeAt(0) + 127397))
    : isoCode;
}
export const codeToLabel = (code: string, country: any) => {
  const select = country.filter((item: { code: string; }) => item.code === code);
  return select.length ? select[0].label : ''
}
export const labelToCode = (label: string, country: any) => {
  const select = country.filter((item: { label: string; }) => item.label === label);
  return select.length ? select[0].code : ''
}

export default [
  { code: 'CN', label: 'China', phone: '86' },
  { code: 'HK', label: 'Hong Kong', phone: '852' },
]